package com.nexonsalary.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * The base class that every database entity in the system inherits from.
 *
 * Instead of repeating the id field and createdAt timestamp in every single class,
 * we define them once here. All entities (Agent, Member, MemberAccount, etc.)
 * extend this class and automatically get these two fields for free.
 *
 * The @MappedSuperclass annotation tells Hibernate: "don't create a separate table
 * for this class — just copy its fields into each subclass table."
 */
@MappedSuperclass
public abstract class BaseEntity {

    /** The unique numeric ID auto-generated by the database for every row. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The exact date and time this record was first saved to the database. */
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    /**
     * Automatically called by Hibernate just before a new record is inserted.
     * Sets the createdAt timestamp so we never have to do it manually.
     *
     * Subclasses can override this method if they need to set additional
     * timestamps (e.g. ClientAgentHistory also sets updatedAt).
     */
    @PrePersist
    public void prePersist() {
        this.createdAt = LocalDateTime.now();
    }

    /** Returns the database ID of this record. */
    public Long getId() {
        return id;
    }

    /** Returns when this record was first created. */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }
}
